version: '3.8'

services:
  back-end:
    image: back-end:latest
    ports:
      - "5001:5001" 
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app


  bot:
    image: bot:latest
    env_file:
      - ./bot/.env
    volumes:
      - ./bot:/app
    environment:
      - BACKEND_API_URL=http://back-end:5001

  front-end:
    image: front-end:latest
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env 
    volumes:
      - ./frontend:/app