version: '3.8'
services:
  back-end:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: team-me-now-production-backend:latest
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  front-end:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: team-me-now-production-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - back-end
    

networks:
  app-network:
    driver: bridge
