FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install gunicorn

COPY . .

RUN useradd -m backendUser
USER backendUser


EXPOSE 5001

CMD ["gunicorn", "--workers=5","--bind","0.0.0.0:5001","server_run:app"]


